Repository pjsip/pjproject, pull requests merged in 2025-04, with the labels that each got.

#4382 pool_i.h: Check available size instead of pointer wrap-around to avoid autological-compare.
  pjlib/include/pj/pool_i.h
Labels: component: pjlib, type:misc/minor-fix

#4383 Deprecate pkgconfig.py
  aconfigure
  aconfigure.ac
Labels: component: common, type:misc/minor-fix

#4372 Android unit test
  pjsip-apps/src/swig/java/android/app-kotlin/build.gradle
  pjsip-apps/src/swig/java/android/app-kotlin/src/main/java/org/pjsip/pjsua2/app_kotlin/MainActivity.kt
  pjsip-apps/src/swig/java/android/app-kotlin/src/main/res/layout/activity_main.xml
  pjsip-apps/src/swig/java/android/app/build.gradle
  pjsip-apps/src/swig/java/android/app/src/androidTest/AndroidManifest.xml
  pjsip-apps/src/swig/java/android/app/src/androidTest/java/org/pjsip/pjsua2/app/Pjsua2Test.java
  pjsip-apps/src/swig/java/android/app/src/main/java/org/pjsip/pjsua2/app/MainActivity.java
  pjsip-apps/src/swig/java/android/app/src/main/java/org/pjsip/pjsua2/app/MyApp.java
  pjsip-apps/src/swig/java/android/app/src/main/res/layout/activity_main.xml
  pjsip-apps/src/swig/java/android/app/src/main/res/layout/dlg_account_config.xml
  pjsip-apps/src/swig/java/android/app/src/main/res/layout/dlg_add_buddy.xml
  pjsip-apps/src/swig/java/android/app/src/main/res/menu/call.xml
  pjsip-apps/src/swig/java/android/app/src/main/res/menu/main.xml
  pjsip-apps/src/swig/java/android/build.gradle
  pjsip-apps/src/swig/java/android/gradle.properties
  pjsip-apps/src/swig/java/android/gradle/wrapper/gradle-wrapper.properties
  pjsip-apps/src/swig/java/android/pjsua2/build.gradle
Labels: component: unit-tests

#4387 Fix typos
  pjlib/include/pj/string.h
  pjsip/include/pjsip/sip_transport.h
Labels: type:misc/minor-fix

#4386 Add support for the LoongArch64 architecture
  aconfigure
  aconfigure.ac
  config.guess
  config.sub
  third_party/webrtc/PJSIP_NOTES
  third_party/webrtc/src/webrtc/typedefs.h
  third_party/webrtc_aec3/PJSIP_NOTES
  third_party/webrtc_aec3/src/rtc_base/system/arch.h
Labels: type: enhancement, component: devops

#4397 Check return value when setting ALSA format
  pjmedia/src/pjmedia-audiodev/alsa_dev.c
Labels: component: pjmedia-audiodev

#4392 remove dead code
  pjsip/include/pjsip/sip_endpoint.h
Labels: component: pjsip, type:misc/minor-fix

#4406 remove dead code
  pjsip-apps/src/samples/footprint.c
  pjsip/include/pjsip-ua/sip_regc.h
Labels: type:misc/minor-fix

#4405 Update some AEC flags docs
  pjmedia/include/pjmedia/config.h
  pjmedia/include/pjmedia/echo.h
Labels: type:misc/minor-fix

#4407 More logging for WebRTC-AEC3
  pjmedia/src/pjmedia/echo_webrtc_aec3.cpp
Labels: type:misc/minor-fix

#4408 File make with j option problem
  build/rules.mak
Labels: component: devops

#4409 Fixed buffer overflow in Android video codec
  pjmedia/src/pjmedia-codec/and_vid_mediacodec.cpp
Labels: component: pjmedia, type: bug

#4410 Fixed incorrect call count upon message sending failure when making call
  pjsip/src/pjsua-lib/pjsua_call.c
Labels: component: pjsua-lib, type: bug

#4411 Use configured public address for SIP transport TCP and TLS
  pjsip/include/pjsip/sip_transport.h
  pjsip/src/pjsip/sip_transport_tcp.c
  pjsip/src/pjsip/sip_transport_tls.c
Labels: component: pjsip
